name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install tree-sitter CLI
        run: npm install -g tree-sitter-cli

      - name: Clone grammar repositories and Build grammars and generate registry
        run: bash batch-git.sh clone

      - name: Package treesitter directory
        run: tar -czf treesitter.tar.gz treesitter/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: treesitter
          path: treesitter.tar.gz

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: treesitter.tar.gz
